# Generated by Django 5.1 on 2024-10-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('queries', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('party_id', models.AutoField(primary_key=True, serialize=False)),
                ('totalVote', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=50)),
                ('logo', models.URLField(default='', max_length=500)),
                ('desc', models.CharField(default='', max_length=1000)),
                ('manifestoLink', models.URLField(default='', max_length=500)),
            ],
        ),
    ]
