# Generated by Django 5.1 on 2024-10-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_party_desc_party_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unique_id',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
    ]
