# Generated by Django 5.1 on 2024-11-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_images/'),
        ),
    ]
