# Generated by Django 5.1.3 on 2024-11-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_face_encoding_profile_face_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='face_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='face_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
